# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CMake
      run: cmake .
    - name: Build
      run: cmake --build .
