# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Submodules
      run: git submodule init && git submodule update
    - name: CMake
      run: cmake .
    - name: Build
      run: cmake --build .
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Submodules
      run: git submodule init && git submodule update
    - name: CMake
      run: cmake . -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=c:\Installs\TracyClient
    - name: Build
      run: cmake --build . --config Release --target INSTALL
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: TracyClient
        path: c:\Installs\TracyClient
